apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.tenantName}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.tenantName}}-sa
  namespace: {{.Values.tenantName}}
automountServiceAccountToken: false